env = Environment(
    CC='gcc',
    CCFLAGS=['-O2'],
    LINKFLAGS=[''])

libhex = env.Object('libhex.c')
hex = env.Object('hex.c')
unhex = env.Object('unhex.c')
mixedradix = env.Object('mixedradix.c')
pat = env.Object('pat.c')

env.Program('hex', libhex + hex)
env.Program('unhex', libhex + unhex)
env.Program('pat', pat + mixedradix + libhex)


env = Environment(
    CC='gcc',
    CCFLAGS=['-O2', '-m32'],
    LINKFLAGS=['-m32'])

libhex = env.Object('libhex32.o', 'libhex.c')
hex = env.Object('hex32.o', 'hex.c')
unhex = env.Object('unhex32.o', 'unhex.c')
mixedradix = env.Object('mixedradix32.o', 'mixedradix.c')
pat = env.Object('pat32.o', 'pat.c')

env.Program('hex32', libhex + hex)
env.Program('unhex32', libhex + unhex)
env.Program('pat32', pat + mixedradix + libhex)


env = Environment(
    CC='i686-w64-mingw32-gcc',
    CCFLAGS=['-O2', '-m32'],
    LINKFLAGS=['-m32'])

libhex = env.Object('libhex_w32.o', 'libhex.c')
hex = env.Object('hex_w32.o', 'hex.c')
unhex = env.Object('unhex_w32.o', 'unhex.c')
mixedradix = env.Object('mixedradix_w32.o', 'mixedradix.c')
pat = env.Object('pat_w32.o', 'pat.c')

env.Program('hex32.exe', libhex + hex)
env.Program('unhex32.exe', libhex + unhex)
env.Program('pat32.exe', pat + mixedradix + libhex)


env = Environment(
    CC='x86_64-w64-mingw32-gcc',
    CCFLAGS=['-O2'],
    LINKFLAGS=[''])

libhex = env.Object('libhex_w.o', 'libhex.c')
hex = env.Object('hex_w.o', 'hex.c')
unhex = env.Object('unhex_w.o', 'unhex.c')
mixedradix = env.Object('mixedradix_w.o', 'mixedradix.c')
pat = env.Object('pat_w.o', 'pat.c')

env.Program('hex.exe', libhex + hex)
env.Program('unhex.exe', libhex + unhex)
env.Program('pat.exe', pat + mixedradix + libhex)
